{"ts": "2025-08-09T22:22:19Z", "error": "UnicodeDecodeError", "message": "'utf-8' codec can't decode byte 0xed in position 32: invalid continuation byte", "auction_context": {"auction_id": "e075747294a143ceb4f52fe5616df62e", "price": 4000000, "timestamp": 1754778053098, "item_bytes": "H4sIAAAAAAAA/2VTS2sTURQ+01ZtUmh9UpdHsKDUxCTNY1J0EZKaFquFJCWLInJn5szMpfMId25I+yPcuaiC4EKIOzfi0kV+Svb9C+KZRGq1MDPn3O+8vvvN..."}, "traceback": "Traceback (most recent call last):\n  File \"/workspaces/AhAveragesPy/__main__.py\", line 39, in decode_item_bytes\n    nbt_file = nbt.nbt.NBTFile(fileobj=io.BytesIO(raw))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 641, in __init__\n    self.parse_file()\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 670, in parse_file\n    self._parse_buffer(self.file)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 489, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 355, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 363, in _parse_buffer\n    self.value = read.decode(\"utf-8\")\n                 ^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 32: invalid continuation byte"}
{"ts": "2025-08-09T22:22:19Z", "error": "UnicodeDecodeError", "message": "'utf-8' codec can't decode byte 0xed in position 30: invalid continuation byte", "auction_context": {"auction_id": "fae93093e027478ea283374c856927dd", "price": 45999998, "timestamp": 1754778063968, "item_bytes": "H4sIAAAAAAAA/2VTTW/TQBAdtwWaVKISHwIu1SIRCVRShdaO2woOIQlJRWmlpChCCKG1PbZXtdeWvVbbK7+BQwFV4oAUbr0gjhzyU3LvX0CM41IiKtmenTcz..."}, "traceback": "Traceback (most recent call last):\n  File \"/workspaces/AhAveragesPy/__main__.py\", line 39, in decode_item_bytes\n    nbt_file = nbt.nbt.NBTFile(fileobj=io.BytesIO(raw))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 641, in __init__\n    self.parse_file()\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 670, in parse_file\n    self._parse_buffer(self.file)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 489, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 355, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 363, in _parse_buffer\n    self.value = read.decode(\"utf-8\")\n                 ^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 30: invalid continuation byte"}
{"ts": "2025-08-09T22:22:36Z", "error": "UnicodeDecodeError", "message": "'utf-8' codec can't decode byte 0xed in position 32: invalid continuation byte", "auction_context": {"auction_id": "e075747294a143ceb4f52fe5616df62e", "price": 4000000, "timestamp": 1754778053098, "item_bytes": "H4sIAAAAAAAA/2VTS2sTURQ+01ZtUmh9UpdHsKDUxCTNY1J0EZKaFquFJCWLInJn5szMpfMId25I+yPcuaiC4EKIOzfi0kV+Svb9C+KZRGq1MDPn3O+8vvvN..."}, "traceback": "Traceback (most recent call last):\n  File \"/workspaces/AhAveragesPy/__main__.py\", line 39, in decode_item_bytes\n    nbt_file = nbt.nbt.NBTFile(fileobj=io.BytesIO(raw))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 641, in __init__\n    self.parse_file()\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 670, in parse_file\n    self._parse_buffer(self.file)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 489, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 355, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 363, in _parse_buffer\n    self.value = read.decode(\"utf-8\")\n                 ^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 32: invalid continuation byte"}
{"ts": "2025-08-09T22:22:36Z", "error": "UnicodeDecodeError", "message": "'utf-8' codec can't decode byte 0xed in position 30: invalid continuation byte", "auction_context": {"auction_id": "fae93093e027478ea283374c856927dd", "price": 45999998, "timestamp": 1754778063968, "item_bytes": "H4sIAAAAAAAA/2VTTW/TQBAdtwWaVKISHwIu1SIRCVRShdaO2woOIQlJRWmlpChCCKG1PbZXtdeWvVbbK7+BQwFV4oAUbr0gjhzyU3LvX0CM41IiKtmenTcz..."}, "traceback": "Traceback (most recent call last):\n  File \"/workspaces/AhAveragesPy/__main__.py\", line 39, in decode_item_bytes\n    nbt_file = nbt.nbt.NBTFile(fileobj=io.BytesIO(raw))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 641, in __init__\n    self.parse_file()\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 670, in parse_file\n    self._parse_buffer(self.file)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 489, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 355, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 363, in _parse_buffer\n    self.value = read.decode(\"utf-8\")\n                 ^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 30: invalid continuation byte"}
{"ts": "2025-08-09T22:23:13Z", "error": "UnicodeDecodeError", "message": "'utf-8' codec can't decode byte 0xed in position 32: invalid continuation byte", "auction_context": {"auction_id": "775d776af6a94568998f0b1c34dc8be3", "price": 7200000, "timestamp": 1754778165461, "item_bytes": "H4sIAAAAAAAA/21TzWsTQRR/21ZtUrDiB3qSESwoNSXNRzctekiTmgZbK0lLDkVkduft7tD9CLMT0l69ePXgoQoFD0K8eRGPHvI3+Bfk3n9BfJOUElTY3Tfv..."}, "traceback": "Traceback (most recent call last):\n  File \"/workspaces/AhAveragesPy/__main__.py\", line 39, in decode_item_bytes\n    nbt_file = nbt.nbt.NBTFile(fileobj=io.BytesIO(raw))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 641, in __init__\n    self.parse_file()\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 670, in parse_file\n    self._parse_buffer(self.file)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 489, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 506, in _parse_buffer\n    tag._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 414, in _parse_buffer\n    self.tags.append(TAGLIST[self.tagID](buffer=buffer))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 355, in __init__\n    self._parse_buffer(buffer)\n  File \"/home/codespace/.local/lib/python3.12/site-packages/nbt/nbt.py\", line 363, in _parse_buffer\n    self.value = read.decode(\"utf-8\")\n                 ^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 32: invalid continuation byte"}
